local isLocalLoggingEnabled = false;

--[[
  WIP - Where are those "speeches" coming from? Are those from Conditional-Speech mod on the workshop?
  https://steamcommunity.com/sharedfiles/filedetails/?id=2398253681
  If yes, why was the mod not credited?
--]]
function GetDialogue(text)
  CreateLogLine("SuperSurvivorDialogue", isLocalLoggingEnabled, "GetDialogue() called");
  return getText("GameSound_Dialogues_SS_" .. text)
end

--- gets a random speech text of a dialogue list
---@param key string key of the speech
---@return string a survivor speech
function GetDialogueSpeech(key)
  CreateLogLine("SuperSurvivorDialogue", isLocalLoggingEnabled, "GetDialogueSpeech() called");
  if (not SurvivorSpeechTable[key]) then
    return "?"
  end

  local result = ZombRand(1, #SurvivorSpeechTable[key]);
  return tostring(SurvivorSpeechTable[key][result]);
end

-- WIP - WifeSpeech is CURRENTLY NOT USED
WifeSpeech = {
  GetDialogue("WifeSpeech1"),
  GetDialogue("WifeSpeech2"),
  GetDialogue("WifeSpeech3"),
  GetDialogue("WifeSpeech4"),
  GetDialogue("WifeSpeech5"),
}

if not SurvivorSpeechTable then
  SurvivorSpeechTable = {}
end

SurvivorSpeechTable["HelloThere"] = {
  GetDialogue("HiThere"),
  GetDialogue("HelloThere"),
  GetDialogue("HelloWord1"),
  GetDialogue("HelloWord2"),
  GetDialogue("HelloWord3"),
  GetDialogue("HelloWord4"),
  GetDialogue("HelloWord5"),
  GetDialogue("HelloWord6"),
  GetDialogue("HelloWord7"),
  GetDialogue("HelloWord8"),
  GetDialogue("HelloWord9"),
  GetDialogue("HelloWord10"),
  GetDialogue("HelloWord11"),
  GetDialogue("HelloWord12"),
  GetDialogue("HelloWord13"),
  GetDialogue("HelloWord14"),
};

SurvivorSpeechTable["OutOfAmmo"] = {
  GetDialogue("OutOfAmmo1"),
  GetDialogue("OutOfAmmo2"),
  GetDialogue("OutOfAmmo3"),
  GetDialogue("OutOfAmmo4"),
};

SurvivorSpeechTable["HowDareYou"] = {
  GetDialogue("HowDareYou1"),
};
SurvivorSpeechTable["WifeIntro"] = {
  GetDialogue("WifeIntro1"),
};

SurvivorSpeechTable["IDontKnowHowDoctor"] = {
  GetDialogue("IDontKnowHowDoctor1"),
};

SurvivorSpeechTable["IfYouThinkSo"] = {
  GetDialogue("IfYouThinkSo1"),
  GetDialogue("IfYouThinkSo2"),
};

SurvivorSpeechTable["SawHimThere"] = {
  GetDialogue("SawHimThere1"),
  GetDialogue("SawHimThere2"),
  GetDialogue("SawHimThere3"),
  GetDialogue("SawHimThere4"),
};

SurvivorSpeechTable["GonnaGetYou"] = {
  GetDialogue("GonnaGetYou1"),
  GetDialogue("GonnaGetYou2"),
  GetDialogue("GonnaGetYou3"),
  GetDialogue("GonnaGetYou4"),
  GetDialogue("GonnaGetYou5"),
};


SurvivorSpeechTable["SeenPlayerIll"] = {
  GetDialogue("SeenPlayerIll1"),
  GetDialogue("SeenPlayerIll2"),
  GetDialogue("SeenPlayerIll3"),
  GetDialogue("SeenPlayerIll4"),
  GetDialogue("SeenPlayerIll5"),
  GetDialogue("SeenPlayerIll6"),
  GetDialogue("SeenPlayerIll7"),
  GetDialogue("SeenPlayerIll8"),
};

SurvivorSpeechTable["SeenPlayerBit"] = {
  GetDialogue("SeenPlayerBit1"),
  GetDialogue("SeenPlayerBit2"),
  GetDialogue("SeenPlayerBit3"),
  GetDialogue("SeenPlayerBit4"),
  GetDialogue("SeenPlayerBit5"),
  GetDialogue("SeenPlayerBit6"),
  GetDialogue("SeenPlayerBit7"),
  GetDialogue("SeenPlayerBit8"),
  GetDialogue("SeenPlayerBit9"),
  GetDialogue("SeenPlayerBit10"),
  GetDialogue("SeenPlayerBit11"),
  GetDialogue("SeenPlayerBit12"),
  GetDialogue("SeenPlayerBit13"),
};

SurvivorSpeechTable["Crying"] = {
  GetDialogue("Crying1"),
  GetDialogue("Crying2"),
  GetDialogue("Crying3"),
  GetDialogue("Crying4"),
  GetDialogue("Crying5"),
  GetDialogue("Crying6"),
  GetDialogue("Crying7"),
  GetDialogue("Crying8"),
  GetDialogue("Crying9"),
  GetDialogue("Crying10"),
  GetDialogue("Crying11"),
  GetDialogue("Crying12"),
  GetDialogue("Crying13"),
  GetDialogue("Crying14"),
  GetDialogue("Crying15"),
  GetDialogue("Crying16"),
};

SurvivorSpeechTable["Tired"] = {
  GetDialogue("Tired1"),
  GetDialogue("Tired2"),
  GetDialogue("Tired3"),
  GetDialogue("Tired4"),
  GetDialogue("Tired5"),
  GetDialogue("Tired6"),
  GetDialogue("Tired7"),
  GetDialogue("Tired8"),
  GetDialogue("Tired9"),
  GetDialogue("Tired10"),
  GetDialogue("Tired11"),
};


SurvivorSpeechTable["VTired"] = {
  GetDialogue("VTired1"),
  GetDialogue("VTired2"),
  GetDialogue("VTired3"),
  GetDialogue("VTired4"),
  GetDialogue("VTired5"),
  GetDialogue("VTired6"),
};



SurvivorSpeechTable["STired"] = {
  GetDialogue("STired1"),
  GetDialogue("STired2"),
  GetDialogue("STired3"),
  GetDialogue("STired4"),
  GetDialogue("STired5"),
  GetDialogue("STired6"),
  GetDialogue("STired7"),
};


SurvivorSpeechTable["Thirsty"] = {
  GetDialogue("Thirsty1"),
  GetDialogue("Thirsty2"),
  GetDialogue("Thirsty3"),
  GetDialogue("Thirsty4"),
  GetDialogue("Thirsty5"),
  GetDialogue("Thirsty6"),
  GetDialogue("Thirsty7"),
  GetDialogue("Thirsty8"),
  GetDialogue("Thirsty9"),
  GetDialogue("Thirsty10"),
};


SurvivorSpeechTable["VThirsty"] = {
  GetDialogue("VThirsty1"),
  GetDialogue("VThirsty2"),
  GetDialogue("VThirsty3"),
  GetDialogue("VThirsty4"),
  GetDialogue("VThirsty5"),
  GetDialogue("VThirsty6"),
  GetDialogue("VThirsty7"),
  GetDialogue("VThirsty8"),
  GetDialogue("VThirsty9"),
  GetDialogue("VThirsty10"),
};


SurvivorSpeechTable["SThirsty"] = {
  GetDialogue("SThirsty1"),
  GetDialogue("SThirsty2"),
  GetDialogue("SThirsty3"),
  GetDialogue("SThirsty4"),
  GetDialogue("SThirsty5"),
  GetDialogue("SThirsty6"),
  GetDialogue("SThirsty7"),
  GetDialogue("SThirsty8"),
  GetDialogue("SThirsty9"),
  GetDialogue("SThirsty10"),
};


SurvivorSpeechTable["Respond"] = {
  GetDialogue("Respond1"),
  GetDialogue("Respond2"),
  GetDialogue("Respond3"),
  GetDialogue("Respond4"),
  GetDialogue("Respond5"),
  GetDialogue("Respond6"),
  GetDialogue("Respond7"),
  GetDialogue("Respond8"),
  GetDialogue("Respond9"),
  GetDialogue("Respond10"),
  GetDialogue("Respond11"),
  GetDialogue("Respond12"),
  GetDialogue("Respond13"),
  GetDialogue("Respond14"),
  GetDialogue("Respond15"),
  GetDialogue("Respond16"),
  GetDialogue("Respond17"),
  GetDialogue("Respond18"),
  GetDialogue("Respond19"),
  GetDialogue("Respond20"),
};

SurvivorSpeechTable["Sick"] = {
  GetDialogue("Sick1"),
  GetDialogue("Sick2"),
};

SurvivorSpeechTable["VSick"] = {
  GetDialogue("VSick1"),
  GetDialogue("VSick2"),
};

SurvivorSpeechTable["SSick"] = {
  GetDialogue("SSick1"),
  GetDialogue("SSick2"),
};

SurvivorSpeechTable["Hungry"] = {
  GetDialogue("Hungry1"),
  GetDialogue("Hungry2"),
  GetDialogue("Hungry3"),
  GetDialogue("Hungry4"),
  GetDialogue("Hungry5"),
  GetDialogue("Hungry6"),
  GetDialogue("Hungry7"),
  GetDialogue("Hungry8"),
  GetDialogue("Hungry9"),
  GetDialogue("Hungry10"),
};

SurvivorSpeechTable["VHungry"] = {
  GetDialogue("VHungry1"),
  GetDialogue("VHungry2"),
  GetDialogue("VHungry3"),
  GetDialogue("VHungry4"),
  GetDialogue("VHungry5"),
  GetDialogue("VHungry6"),
  GetDialogue("VHungry7"),
  GetDialogue("VHungry8"),
  GetDialogue("VHungry9"),
  GetDialogue("VHungry10"),
};


SurvivorSpeechTable["Starving"] = {
  GetDialogue("Starving1"),
  GetDialogue("Starving2"),
  GetDialogue("Starving3"),
  GetDialogue("Starving4"),
  GetDialogue("Starving5"),
  GetDialogue("Starving6"),
  GetDialogue("Starving7"),
  GetDialogue("Starving8"),
  GetDialogue("Starving9"),
  GetDialogue("Starving10"),
};

SurvivorSpeechTable["Roger"] = {
  GetDialogue("Roger1"),
  GetDialogue("Roger2"),
  GetDialogue("Roger3"),
  GetDialogue("Roger4"),
  GetDialogue("Roger5"),
  GetDialogue("Roger6"),
  GetDialogue("Roger7"),
  GetDialogue("Roger8"),
  GetDialogue("Roger9"),
  GetDialogue("Roger10"),
  GetDialogue("Roger11"),
  GetDialogue("Roger12"),
  GetDialogue("Roger13"),
  GetDialogue("Roger14"),
  GetDialogue("Roger15"),
  GetDialogue("Roger16"),
  GetDialogue("Roger17"),
  GetDialogue("Roger18"),
  GetDialogue("Roger19"),
  GetDialogue("Roger20"),
  GetDialogue("Roger21"),
  GetDialogue("Roger22"),
  GetDialogue("Roger23"),
  GetDialogue("Roger24"),
  GetDialogue("Roger25"),
  GetDialogue("Roger26"),
  GetDialogue("Roger27"),
  GetDialogue("Roger28"),
  GetDialogue("Roger29"),
  GetDialogue("Roger30"),
};

SurvivorSpeechTable["No"] = {
  GetDialogue("No1"),
  GetDialogue("No2"),
  GetDialogue("No3"),
  GetDialogue("No4"),
  GetDialogue("No5"),
  GetDialogue("No6"),
  GetDialogue("No7"),
  GetDialogue("No8"),
  GetDialogue("No9"),
  GetDialogue("No10"),
  GetDialogue("No11"),
  GetDialogue("No12"),
};

SurvivorSpeechTable["Thanks"] = {
  GetDialogue("Thanks1"),
  GetDialogue("Thanks2"),
  GetDialogue("Thanks3"),
  GetDialogue("Thanks4"),
  GetDialogue("Thanks5"),
  GetDialogue("Thanks6"),
  GetDialogue("Thanks7"),
  GetDialogue("Thanks8"),
};

SurvivorSpeechTable["HitByPlayer"] = {
  GetDialogue("HitByPlayer1"),
  GetDialogue("HitByPlayer2"),
  GetDialogue("HitByPlayer3"),
  GetDialogue("HitByPlayer4"),
  GetDialogue("HitByPlayer5"),
  GetDialogue("HitByPlayer6"),
  GetDialogue("HitByPlayer7"),
  GetDialogue("HitByPlayer8"),
  GetDialogue("HitByPlayer9"),
  GetDialogue("HitByPlayer10"),
  GetDialogue("HitByPlayer11"),
  GetDialogue("HitByPlayer12"),
  GetDialogue("HitByPlayer13"),
  GetDialogue("HitByPlayer14"),
  GetDialogue("HitByPlayer15"),
  GetDialogue("HitByPlayer16"),
  GetDialogue("HitByPlayer17"),
  GetDialogue("HitByPlayer18"),
  GetDialogue("HitByPlayer19"),
  GetDialogue("HitByPlayer20"),
  GetDialogue("HitByPlayer21"),
  GetDialogue("HitByPlayer22"),
  GetDialogue("HitByPlayer23"),
  GetDialogue("HitByPlayer24"),
  GetDialogue("HitByPlayer25"),
  GetDialogue("HitByPlayer26"),
  GetDialogue("HitByPlayer27"),
  GetDialogue("HitByPlayer28"),
  GetDialogue("HitByPlayer29"),
};


SurvivorSpeechTable["SeenFirstZombie"] = {
  GetDialogue("SeenFirstZombie1"),
  GetDialogue("SeenFirstZombie2"),
  GetDialogue("SeenFirstZombie3"),
  GetDialogue("SeenFirstZombie4"),
  GetDialogue("SeenFirstZombie5"),
  GetDialogue("SeenFirstZombie6"),
  GetDialogue("SeenFirstZombie7"),
  GetDialogue("SeenFirstZombie8"),
  GetDialogue("SeenFirstZombie9"),
  GetDialogue("SeenFirstZombie10"),
  GetDialogue("SeenFirstZombie11"),
  GetDialogue("SeenFirstZombie12"),
  GetDialogue("SeenFirstZombie13"),
  GetDialogue("SeenFirstZombie14"),
  GetDialogue("SeenFirstZombie15"),
  GetDialogue("SeenFirstZombie16"),
  GetDialogue("SeenFirstZombie17"),
  GetDialogue("SeenFirstZombie18"),
};


SurvivorSpeechTable["IdleChatter"] = {
  GetDialogue("IdleChatter1"),
  GetDialogue("IdleChatter2"),
  GetDialogue("IdleChatter3"),
  GetDialogue("IdleChatter4"),
  GetDialogue("IdleChatter5"),
  GetDialogue("IdleChatter6"),
  GetDialogue("IdleChatter7"),
  GetDialogue("IdleChatter8"),
  GetDialogue("IdleChatter9"),
  GetDialogue("IdleChatter10"),
  GetDialogue("IdleChatter11"),
  GetDialogue("IdleChatter12"),
  GetDialogue("IdleChatter13"),
  GetDialogue("IdleChatter14"),
  GetDialogue("IdleChatter15"),
  GetDialogue("IdleChatter16"),
  GetDialogue("IdleChatter17"),
  GetDialogue("IdleChatter18"),
  GetDialogue("IdleChatter19"),
  GetDialogue("IdleChatter20"),
  GetDialogue("IdleChatter21"),
  GetDialogue("IdleChatter22"),
  GetDialogue("IdleChatter23"),
  GetDialogue("IdleChatter24"),
  GetDialogue("IdleChatter25"),
  GetDialogue("IdleChatter26"),
  GetDialogue("IdleChatter27"),
  GetDialogue("IdleChatter28"),
  GetDialogue("IdleChatter29"),
  GetDialogue("IdleChatter30"),
  GetDialogue("IdleChatter31"),
  GetDialogue("IdleChatter32"),
  GetDialogue("IdleChatter33"),
  GetDialogue("IdleChatter34"),
  GetDialogue("IdleChatter35"),
  GetDialogue("IdleChatter36"),
  GetDialogue("IdleChatter37"),
  GetDialogue("IdleChatter38"),
  GetDialogue("IdleChatter39"),
  GetDialogue("IdleChatter40"),
  GetDialogue("IdleChatter41"),
  GetDialogue("IdleChatter42"),
  GetDialogue("IdleChatter43"),
  GetDialogue("IdleChatter44"),
  GetDialogue("IdleChatter45"),
  GetDialogue("IdleChatter46"),
  GetDialogue("IdleChatter47"),
  GetDialogue("IdleChatter48"),
  GetDialogue("IdleChatter49"),
  GetDialogue("IdleChatter50"),
  GetDialogue("IdleChatter51"),
  GetDialogue("IdleChatter52"),
  GetDialogue("IdleChatter53"),
  GetDialogue("IdleChatter54"),
  GetDialogue("IdleChatter55"),
  GetDialogue("IdleChatter56"),
  GetDialogue("IdleChatter57"),
  GetDialogue("IdleChatter58"),
  GetDialogue("IdleChatter59"),
  GetDialogue("IdleChatter60"),
  GetDialogue("IdleChatter61"),
  GetDialogue("IdleChatter62"),
  GetDialogue("IdleChatter63"),
  GetDialogue("IdleChatter64"),
  GetDialogue("IdleChatter65"),
  GetDialogue("IdleChatter66"),
  GetDialogue("IdleChatter67"),
  GetDialogue("IdleChatter68"),
  GetDialogue("IdleChatter69"),
  GetDialogue("IdleChatter70"),
  GetDialogue("IdleChatter71"),
  GetDialogue("IdleChatter72"),
  GetDialogue("IdleChatter73"),
  GetDialogue("IdleChatter74"),
  GetDialogue("IdleChatter75"),
  GetDialogue("IdleChatter76"),
  GetDialogue("IdleChatter77"),
  GetDialogue("IdleChatter78"),
  GetDialogue("IdleChatter79"),
  GetDialogue("IdleChatter80"),
  GetDialogue("IdleChatter81"),
  GetDialogue("IdleChatter82"),
  GetDialogue("IdleChatter83"),
  GetDialogue("IdleChatter84"),
  GetDialogue("IdleChatter85"),
  GetDialogue("IdleChatter86"),
  GetDialogue("IdleChatter87"),
  GetDialogue("IdleChatter88"),
  GetDialogue("IdleChatter89"),
  GetDialogue("IdleChatter90"),
  GetDialogue("IdleChatter91"),
  GetDialogue("IdleChatter92"),
  GetDialogue("IdleChatter93"),
  GetDialogue("IdleChatter94"),
  GetDialogue("IdleChatter95"),
  GetDialogue("IdleChatter96"),
  GetDialogue("IdleChatter97"),
  GetDialogue("IdleChatter98"),
  GetDialogue("IdleChatter99"),
  GetDialogue("IdleChatter100"),
  GetDialogue("IdleChatter101"),
  GetDialogue("IdleChatter102"),
  GetDialogue("IdleChatter103"),
  GetDialogue("IdleChatter104"),
  GetDialogue("IdleChatter105"),
  GetDialogue("IdleChatter106"),
  GetDialogue("IdleChatter107"),
  GetDialogue("IdleChatter108"),
  GetDialogue("IdleChatter109"),
  GetDialogue("IdleChatter110"),
  GetDialogue("IdleChatter111"),
  GetDialogue("IdleChatter112"),
  GetDialogue("IdleChatter113"),
  GetDialogue("IdleChatter114"),
  GetDialogue("IdleChatter115"),
  GetDialogue("IdleChatter116"),
  GetDialogue("IdleChatter117"),
  GetDialogue("IdleChatter118"),
  GetDialogue("IdleChatter119"),
  GetDialogue("IdleChatter120"),
  GetDialogue("IdleChatter121"),
  GetDialogue("IdleChatter122"),
  GetDialogue("IdleChatter123"),
  GetDialogue("IdleChatter124"),
  GetDialogue("IdleChatter125"),
  GetDialogue("IdleChatter126"),
  GetDialogue("IdleChatter127"),
  GetDialogue("IdleChatter128"),
  GetDialogue("IdleChatter129"),
  GetDialogue("IdleChatter130"),
  GetDialogue("IdleChatter131"),
  GetDialogue("IdleChatter132"),
  GetDialogue("IdleChatter133"),
  GetDialogue("IdleChatter134"),
  GetDialogue("IdleChatter135"),
  GetDialogue("IdleChatter136"),
  GetDialogue("IdleChatter137"),
  GetDialogue("IdleChatter138"),
  GetDialogue("IdleChatter139"),
  GetDialogue("IdleChatter140"),
};


SurvivorSpeechTable["PreZombieChatter"] = {
  GetDialogue("PreZombieChatter1"),
  GetDialogue("PreZombieChatter2"),
  GetDialogue("PreZombieChatter3"),
  GetDialogue("PreZombieChatter4"),
  GetDialogue("PreZombieChatter5"),
  GetDialogue("PreZombieChatter6"),
  GetDialogue("PreZombieChatter7"),
  GetDialogue("PreZombieChatter8"),
  GetDialogue("PreZombieChatter9"),
  GetDialogue("PreZombieChatter10"),
  GetDialogue("PreZombieChatter11"),
  GetDialogue("PreZombieChatter12"),
  GetDialogue("PreZombieChatter13"),
  GetDialogue("PreZombieChatter14"),
};


SurvivorSpeechTable["Hurt"] = {
  GetDialogue("Hurt1"),
  GetDialogue("Hurt2"),
  GetDialogue("Hurt3"),
  GetDialogue("Hurt4"),
  GetDialogue("Hurt5"),
  GetDialogue("Hurt6"),
  GetDialogue("Hurt7"),
  GetDialogue("Hurt8"),
  GetDialogue("Hurt9"),
  GetDialogue("Hurt10"),
  GetDialogue("Hurt11"),
  GetDialogue("Hurt12"),
  GetDialogue("Hurt13"),
  GetDialogue("Hurt14"),
  GetDialogue("Hurt15"),
  GetDialogue("Hurt16"),
  GetDialogue("Hurt17"),
  GetDialogue("Hurt18"),
};


SurvivorSpeechTable["Injured"] = {
  GetDialogue("Injured1"),
  GetDialogue("Injured2"),
  GetDialogue("Injured3"),
  GetDialogue("Injured4"),
  GetDialogue("Injured5"),
  GetDialogue("Injured6"),
  GetDialogue("Injured7"),
  GetDialogue("Injured8"),
  GetDialogue("Injured9"),
  GetDialogue("Injured10"),
  GetDialogue("Injured11"),
  GetDialogue("Injured12"),
  GetDialogue("Injured13"),
  GetDialogue("Injured14"),
  GetDialogue("Injured15"),
  GetDialogue("Injured16"),
  GetDialogue("Injured17"),
  GetDialogue("Injured18"),
  GetDialogue("Injured19"),
  GetDialogue("Injured20"),
};



SurvivorSpeechTable["BadInjured"] = {
  GetDialogue("BadInjured1"),
  GetDialogue("BadInjured2"),
  GetDialogue("BadInjured3"),
  GetDialogue("BadInjured4"),
  GetDialogue("BadInjured5"),
  GetDialogue("BadInjured6"),
  GetDialogue("BadInjured7"),
  GetDialogue("BadInjured8"),
  GetDialogue("BadInjured9"),
  GetDialogue("BadInjured10"),
  GetDialogue("BadInjured11"),
  GetDialogue("BadInjured12"),
  GetDialogue("BadInjured13"),
  GetDialogue("BadInjured14"),
  GetDialogue("BadInjured15"),
  GetDialogue("BadInjured16"),
  GetDialogue("BadInjured17"),
};


SurvivorSpeechTable["SeriousInjured"] = {
  GetDialogue("SeriousInjured1"),
  GetDialogue("SeriousInjured2"),
  GetDialogue("SeriousInjured3"),
  GetDialogue("SeriousInjured4"),
  GetDialogue("SeriousInjured5"),
  GetDialogue("SeriousInjured6"),
  GetDialogue("SeriousInjured7"),
  GetDialogue("SeriousInjured8"),
  GetDialogue("SeriousInjured9"),
  GetDialogue("SeriousInjured10"),
  GetDialogue("SeriousInjured11"),
  GetDialogue("SeriousInjured12"),
  GetDialogue("SeriousInjured13"),
  GetDialogue("SeriousInjured14"),
  GetDialogue("SeriousInjured15"),
  GetDialogue("SeriousInjured16"),
  GetDialogue("SeriousInjured17"),
  GetDialogue("SeriousInjured18"),
  GetDialogue("SeriousInjured19"),
  GetDialogue("SeriousInjured20"),
  GetDialogue("SeriousInjured21"),
  GetDialogue("SeriousInjured22"),
  GetDialogue("SeriousInjured23"),
};


SurvivorSpeechTable["FatalInjured"] = {
  GetDialogue("FatalInjured1"),
  GetDialogue("FatalInjured2"),
  GetDialogue("FatalInjured3"),
  GetDialogue("FatalInjured4"),
  GetDialogue("FatalInjured5"),
  GetDialogue("FatalInjured6"),
  GetDialogue("FatalInjured7"),
  GetDialogue("FatalInjured8"),
  GetDialogue("FatalInjured9"),
  GetDialogue("FatalInjured10"),
  GetDialogue("FatalInjured11"),
  GetDialogue("FatalInjured12"),
  GetDialogue("FatalInjured13"),
  GetDialogue("FatalInjured14"),
  GetDialogue("FatalInjured15"),
  GetDialogue("FatalInjured16"),
  GetDialogue("FatalInjured17"),
};


SurvivorSpeechTable["FinalWords"] = {
  GetDialogue("FinalWords1"),
  GetDialogue("FinalWords2"),
  GetDialogue("FinalWords3"),
  GetDialogue("FinalWords4"),
  GetDialogue("FinalWords5"),
  GetDialogue("FinalWords6"),
  GetDialogue("FinalWords7"),
  GetDialogue("FinalWords8"),
  GetDialogue("FinalWords9"),
  GetDialogue("FinalWords10"),
  GetDialogue("FinalWords11"),
  GetDialogue("FinalWords12"),
  GetDialogue("FinalWords13"),
  GetDialogue("FinalWords14"),
  GetDialogue("FinalWords15"),
  GetDialogue("FinalWords16"),
  GetDialogue("FinalWords17"),
  GetDialogue("FinalWords18"),
  GetDialogue("FinalWords19"),
  GetDialogue("FinalWords20"),
  GetDialogue("FinalWords21"),
  GetDialogue("FinalWords22"),
  GetDialogue("FinalWords23"),
  GetDialogue("FinalWords24"),
  GetDialogue("FinalWords25"),
  GetDialogue("FinalWords26"),
  GetDialogue("FinalWords27"),
  GetDialogue("FinalWords28"),
  GetDialogue("FinalWords29"),
  GetDialogue("FinalWords30"),
  GetDialogue("FinalWords31"),
};



SurvivorSpeechTable["NameText"] = {
  GetDialogue("NameText1"),
  GetDialogue("NameText2"),
  GetDialogue("NameText3"),
  GetDialogue("NameText4"),
  GetDialogue("NameText5"),
  GetDialogue("NameText6"),
  GetDialogue("NameText7"),
  GetDialogue("NameText8"),
  GetDialogue("NameText9"),
};


SurvivorSpeechTable["Greetings"] = {
  GetDialogue("Greetings1"),
  GetDialogue("Greetings2"),
  GetDialogue("Greetings3"),
  GetDialogue("Greetings4"),
  GetDialogue("Greetings5"),
  GetDialogue("Greetings6"),
  GetDialogue("Greetings7"),
  GetDialogue("Greetings8"),
  GetDialogue("Greetings9"),
  GetDialogue("Greetings10"),
  GetDialogue("Greetings11"),
  GetDialogue("Greetings12"),
  GetDialogue("Greetings13"),
  GetDialogue("Greetings14"),
  GetDialogue("Greetings15"),
  GetDialogue("Greetings16"),
  GetDialogue("Greetings17"),
  GetDialogue("Greetings18"),
  GetDialogue("Greetings19"),
  GetDialogue("Greetings20"),
  GetDialogue("Greetings21"),
  GetDialogue("Greetings22"),
  GetDialogue("Greetings23"),
  GetDialogue("Greetings24"),
  GetDialogue("Greetings25"),
  GetDialogue("Greetings26"),
  GetDialogue("Greetings27"),
  GetDialogue("Greetings28"),
  GetDialogue("Greetings29"),
  GetDialogue("Greetings30"),
  GetDialogue("Greetings31"),
  GetDialogue("Greetings32"),
  GetDialogue("Greetings33"),
  GetDialogue("Greetings34"),
  GetDialogue("Greetings35"),
  GetDialogue("Greetings36"),
  GetDialogue("Greetings37"),
  GetDialogue("Greetings38"),
  GetDialogue("Greetings39"),
  GetDialogue("Greetings40"),
  GetDialogue("Greetings41"),
  GetDialogue("Greetings42"),
  GetDialogue("Greetings43"),
  GetDialogue("Greetings44"),
  GetDialogue("Greetings45"),
  GetDialogue("Greetings46"),
};


SurvivorSpeechTable["WantToHide"] = {
  GetDialogue("WantToHide1"),
  GetDialogue("WantToHide2"),
  GetDialogue("WantToHide3"),
  GetDialogue("WantToHide4"),
  GetDialogue("WantToHide5"),
  GetDialogue("WantToHide6"),
  GetDialogue("WantToHide7"),
  GetDialogue("WantToHide8"),
  GetDialogue("WantToHide9"),
  GetDialogue("WantToHide10"),
  GetDialogue("WantToHide11"),
  GetDialogue("WantToHide12"),
  GetDialogue("WantToHide13"),
  GetDialogue("WantToHide14"),
  GetDialogue("WantToHide15"),
  GetDialogue("WantToHide16"),
  GetDialogue("WantToHide17"),
  GetDialogue("WantToHide18"),
  GetDialogue("WantToHide19"),
  GetDialogue("WantToHide20"),
  GetDialogue("WantToHide21"),
  GetDialogue("WantToHide22"),
  GetDialogue("WantToHide23"),
};



SurvivorSpeechTable["FoundHidingPlace"] = {
  GetDialogue("FoundHidingPlace1"),
  GetDialogue("FoundHidingPlace2"),
  GetDialogue("FoundHidingPlace3"),
  GetDialogue("FoundHidingPlace4"),
  GetDialogue("FoundHidingPlace5"),
  GetDialogue("FoundHidingPlace6"),
  GetDialogue("FoundHidingPlace7"),
  GetDialogue("FoundHidingPlace8"),
  GetDialogue("FoundHidingPlace9"),
  GetDialogue("FoundHidingPlace10"),
  GetDialogue("FoundHidingPlace11"),
  GetDialogue("FoundHidingPlace12"),
  GetDialogue("FoundHidingPlace13"),
  GetDialogue("FoundHidingPlace14"),
  GetDialogue("FoundHidingPlace15"),
  GetDialogue("FoundHidingPlace16"),
  GetDialogue("FoundHidingPlace17"),
  GetDialogue("FoundHidingPlace18"),
  GetDialogue("FoundHidingPlace19"),
  GetDialogue("FoundHidingPlace20"),
  GetDialogue("FoundHidingPlace21"),
  GetDialogue("FoundHidingPlace22"),
  GetDialogue("FoundHidingPlace23"),
  GetDialogue("FoundHidingPlace24"),
  GetDialogue("FoundHidingPlace25"),
  GetDialogue("FoundHidingPlace26"),
  GetDialogue("FoundHidingPlace27"),
  GetDialogue("FoundHidingPlace28"),
  GetDialogue("FoundHidingPlace29"),
  GetDialogue("FoundHidingPlace30"),
  GetDialogue("FoundHidingPlace31"),
  GetDialogue("FoundHidingPlace32"),
  GetDialogue("FoundHidingPlace33"),
  GetDialogue("FoundHidingPlace34"),
  GetDialogue("FoundHidingPlace35"),
  GetDialogue("FoundHidingPlace36"),
  GetDialogue("FoundHidingPlace37"),
  GetDialogue("FoundHidingPlace38"),
  GetDialogue("FoundHidingPlace39"),
  GetDialogue("FoundHidingPlace40"),
  GetDialogue("FoundHidingPlace41"),
};


SurvivorSpeechTable["NoWhereToHide"] = {
  GetDialogue("NoWhereToHide1"),
  GetDialogue("NoWhereToHide2"),
  GetDialogue("NoWhereToHide3"),
  GetDialogue("NoWhereToHide4"),
  GetDialogue("NoWhereToHide5"),
  GetDialogue("NoWhereToHide6"),
  GetDialogue("NoWhereToHide7"),
  GetDialogue("NoWhereToHide8"),
  GetDialogue("NoWhereToHide9"),
  GetDialogue("NoWhereToHide10"),
  GetDialogue("NoWhereToHide11"),
  GetDialogue("NoWhereToHide12"),
  GetDialogue("NoWhereToHide13"),
  GetDialogue("NoWhereToHide14"),
  GetDialogue("NoWhereToHide15"),
  GetDialogue("NoWhereToHide16"),
  GetDialogue("NoWhereToHide17"),
  GetDialogue("NoWhereToHide18"),
  GetDialogue("NoWhereToHide19"),
  GetDialogue("NoWhereToHide20"),
  GetDialogue("NoWhereToHide21"),
  GetDialogue("NoWhereToHide22"),
  GetDialogue("NoWhereToHide23"),
};


SurvivorSpeechTable["Panic"] = {
  GetDialogue("Panic1"),
  GetDialogue("Panic2"),
  GetDialogue("Panic3"),
  GetDialogue("Panic4"),
  GetDialogue("Panic5"),
  GetDialogue("Panic6"),
  GetDialogue("Panic7"),
  GetDialogue("Panic8"),
  GetDialogue("Panic9"),
  GetDialogue("Panic10"),
  GetDialogue("Panic11"),
  GetDialogue("Panic12"),
  GetDialogue("Panic13"),
  GetDialogue("Panic14"),
  GetDialogue("Panic15"),
  GetDialogue("Panic16"),
  GetDialogue("Panic17"),
  GetDialogue("Panic18"),
  GetDialogue("Panic19"),
  GetDialogue("Panic20"),
  GetDialogue("Panic21"),
  GetDialogue("Panic22"),
  GetDialogue("Panic23"),
};


SurvivorSpeechTable["Scared"] = {
  GetDialogue("Scared1"),
  GetDialogue("Scared2"),
  GetDialogue("Scared3"),
  GetDialogue("Scared4"),
  GetDialogue("Scared5"),
  GetDialogue("Scared6"),
  GetDialogue("Scared7"),
  GetDialogue("Scared8"),
  GetDialogue("Scared9"),
  GetDialogue("Scared10"),
  GetDialogue("Scared11"),
  GetDialogue("Scared12"),
  GetDialogue("Scared13"),
  GetDialogue("Scared14"),
  GetDialogue("Scared15"),
  GetDialogue("Scared16"),
  GetDialogue("Scared17"),
  GetDialogue("Scared18"),
  GetDialogue("Scared19"),
  GetDialogue("Scared20"),
};


SurvivorSpeechTable["Screem"] = {
  GetDialogue("Screem1"),
  GetDialogue("Screem2"),
  GetDialogue("Screem3"),
  GetDialogue("Screem4"),
  GetDialogue("Screem5"),
  GetDialogue("Screem6"),
  GetDialogue("Screem7"),
  GetDialogue("Screem8"),
  GetDialogue("Screem9"),
  GetDialogue("Screem10"),
  GetDialogue("Screem11"),
  GetDialogue("Screem12"),
  GetDialogue("Screem13"),
  GetDialogue("Screem14"),
  GetDialogue("Screem15"),
  GetDialogue("Screem16"),
  GetDialogue("Screem17"),
  GetDialogue("Screem18"),
  GetDialogue("Screem19"),
  GetDialogue("Screem20"),
  GetDialogue("Screem21"),
  GetDialogue("Screem22"),
  GetDialogue("Screem23"),
};



SurvivorSpeechTable["Attack"] = {
  GetDialogue("Attack1"),
  GetDialogue("Attack2"),
  GetDialogue("Attack3"),
  GetDialogue("Attack4"),
  GetDialogue("Attack5"),
  GetDialogue("Attack6"),
  GetDialogue("Attack7"),
  GetDialogue("Attack8"),
  GetDialogue("Attack9"),
  GetDialogue("Attack10"),
  GetDialogue("Attack11"),
  GetDialogue("Attack12"),
  GetDialogue("Attack13"),
  GetDialogue("Attack14"),
  GetDialogue("Attack15"),
  GetDialogue("Attack16"),
  GetDialogue("Attack17"),
  GetDialogue("Attack18"),
  GetDialogue("Attack19"),
  GetDialogue("Attack20"),
  GetDialogue("Attack21"),
  GetDialogue("Attack22"),
  GetDialogue("Attack23"),
  GetDialogue("Attack24"),
  GetDialogue("Attack25"),
  GetDialogue("Attack26"),
  GetDialogue("Attack27"),
  GetDialogue("Attack28"),
  GetDialogue("Attack29"),
  GetDialogue("Attack30"),
  GetDialogue("Attack31"),
  GetDialogue("Attack32"),
  GetDialogue("Attack33"),
  GetDialogue("Attack34"),
  GetDialogue("Attack35"),
  GetDialogue("Attack36"),
  GetDialogue("Attack37"),
  GetDialogue("Attack38"),
};


SurvivorSpeechTable["AttackS"] = {
  GetDialogue("AttackS1"),
  GetDialogue("AttackS2"),
  GetDialogue("AttackS3"),
  GetDialogue("AttackS4"),
  GetDialogue("AttackS5"),
  GetDialogue("AttackS6"),
  GetDialogue("AttackS7"),
  GetDialogue("AttackS8"),
  GetDialogue("AttackS9"),
  GetDialogue("AttackS10"),
  GetDialogue("AttackS11"),
  GetDialogue("AttackS12"),
  GetDialogue("AttackS13"),
  GetDialogue("AttackS14"),
  GetDialogue("AttackS15"),
  GetDialogue("AttackS16"),
  GetDialogue("AttackS17"),
  GetDialogue("AttackS18"),
  GetDialogue("AttackS19"),
  GetDialogue("AttackS20"),
  GetDialogue("AttackS21"),
  GetDialogue("AttackS22"),
  GetDialogue("AttackS23"),
  GetDialogue("AttackS24"),
  GetDialogue("AttackS25"),
  GetDialogue("AttackS26"),
  GetDialogue("AttackS27"),
  GetDialogue("AttackS28"),
  GetDialogue("AttackS29"),
};


SurvivorSpeechTable["Traitor"] = {
  GetDialogue("Traitor1"),
  GetDialogue("Traitor2"),
  GetDialogue("Traitor3"),
  GetDialogue("Traitor4"),
  GetDialogue("Traitor5"),
  GetDialogue("Traitor6"),
  GetDialogue("Traitor7"),
  GetDialogue("Traitor8"),
  GetDialogue("Traitor9"),
  GetDialogue("Traitor10"),
  GetDialogue("Traitor11"),
  GetDialogue("Traitor12"),
  GetDialogue("Traitor13"),
  GetDialogue("Traitor14"),
  GetDialogue("Traitor15"),
  GetDialogue("Traitor16"),
  GetDialogue("Traitor17"),
  GetDialogue("Traitor18"),
  GetDialogue("Traitor19"),
  GetDialogue("Traitor20"),
  GetDialogue("Traitor21"),
  GetDialogue("Traitor22"),
};


SurvivorSpeechTable["LookingForZombie"] = {
  GetDialogue("LookingForZombie1"),
  GetDialogue("LookingForZombie2"),
  GetDialogue("LookingForZombie3"),
  GetDialogue("LookingForZombie4"),
  GetDialogue("LookingForZombie5"),
  GetDialogue("LookingForZombie6"),
  GetDialogue("LookingForZombie7"),
  GetDialogue("LookingForZombie8"),
  GetDialogue("LookingForZombie9"),
  GetDialogue("LookingForZombie10"),
  GetDialogue("LookingForZombie11"),
  GetDialogue("LookingForZombie12"),
  GetDialogue("LookingForZombie13"),
  GetDialogue("LookingForZombie14"),
  GetDialogue("LookingForZombie15"),
};


SurvivorSpeechTable["FoundSurvivor"] = {
  GetDialogue("FoundSurvivor1"),
  GetDialogue("FoundSurvivor2"),
  GetDialogue("FoundSurvivor3"),
  GetDialogue("FoundSurvivor4"),
  GetDialogue("FoundSurvivor5"),
  GetDialogue("FoundSurvivor6"),
  GetDialogue("FoundSurvivor7"),
  GetDialogue("FoundSurvivor8"),
  GetDialogue("FoundSurvivor9"),
  GetDialogue("FoundSurvivor10"),
  GetDialogue("FoundSurvivor11"),
  GetDialogue("FoundSurvivor12"),
  GetDialogue("FoundSurvivor13"),
  GetDialogue("FoundSurvivor14"),
  GetDialogue("FoundSurvivor15"),
  GetDialogue("FoundSurvivor16"),
  GetDialogue("FoundSurvivor17"),
  GetDialogue("FoundSurvivor18"),
  GetDialogue("FoundSurvivor19"),
  GetDialogue("FoundSurvivor20"),
  GetDialogue("FoundSurvivor21"),
  GetDialogue("FoundSurvivor22"),
  GetDialogue("FoundSurvivor23"),
  GetDialogue("FoundSurvivor24"),
  GetDialogue("FoundSurvivor25"),
  GetDialogue("FoundSurvivor26"),
  GetDialogue("FoundSurvivor27"),
  GetDialogue("FoundSurvivor28"),
  GetDialogue("FoundSurvivor29"),
  GetDialogue("FoundSurvivor30"),
  GetDialogue("FoundSurvivor31"),
  GetDialogue("FoundSurvivor32"),
  GetDialogue("FoundSurvivor33"),
  GetDialogue("FoundSurvivor34"),
};


SurvivorSpeechTable["FoundZombie"] = {
  GetDialogue("FoundZombie1"),
  GetDialogue("FoundZombie2"),
  GetDialogue("FoundZombie3"),
  GetDialogue("FoundZombie4"),
  GetDialogue("FoundZombie5"),
  GetDialogue("FoundZombie6"),
  GetDialogue("FoundZombie7"),
  GetDialogue("FoundZombie8"),
  GetDialogue("FoundZombie9"),
  GetDialogue("FoundZombie10"),
  GetDialogue("FoundZombie11"),
  GetDialogue("FoundZombie12"),
  GetDialogue("FoundZombie13"),
  GetDialogue("FoundZombie14"),
  GetDialogue("FoundZombie15"),
  GetDialogue("FoundZombie16"),
  GetDialogue("FoundZombie17"),
  GetDialogue("FoundZombie18"),
  GetDialogue("FoundZombie19"),
};
