-- Cows: Global Survivor Orders
-- Cows: This was moved out of the "SuperSurvivorUtilities.lua" file.
Orders = {
    "Barricade",
    "Chop Wood",
    "Clean Up Inventory",
    "Doctor",
    "Explore",
    "Follow",
    "Farming",
    "Forage",
    "Gather Wood",
    "Go Find Food",
    "Go Find Water",
    "Go Find Weapon",
    "Guard",
    "Lock Doors",
    "Loot Room",
    "Patrol",
    "Sort Loot Into Base",
    "Stand Ground",
    "Stop",
    "Dismiss",
    "Relax",
    "Return To Base",
    "Pile Corpses",
};

OrderDesc = {
    ["Barricade"] = getText("ContextMenu_SS_OrderDesc_Barricade"),
    ["Farming"] = getText("ContextMenu_SS_OrderDesc_Farming"),
    ["Chop Wood"] = getText("ContextMenu_SS_OrderDesc_Chop_Wood"),
    ["Explore"] = getText("ContextMenu_SS_OrderDesc_Explore"),
    ["Follow"] = getText("ContextMenu_SS_OrderDesc_Follow"),
    ["Forage"] = getText("ContextMenu_SS_OrderDesc_Forage"),
    ["Guard"] = getText("ContextMenu_SS_OrderDesc_Guard"),
    ["Patrol"] = getText("ContextMenu_SS_OrderDesc_Patrol"),
    ["Stand Ground"] = getText("ContextMenu_SS_OrderDesc_Stand_Ground"),
    ["Loot Room"] = getText("ContextMenu_SS_OrderDesc_Loot_Room"),
    ["Lock Doors"] = getText("ContextMenu_SS_OrderDesc_Lock_Doors"),
    ["Doctor"] = getText("ContextMenu_SS_OrderDesc_Doctor"),
    ["Go Find Food"] = getText("ContextMenu_SS_OrderDesc_Go_Find_Food"),
    ["Go Find Weapon"] = getText("ContextMenu_SS_OrderDesc_Go_Find_Weapon"),
    ["Go Find Water"] = getText("ContextMenu_SS_OrderDesc_Go_Find_Water"),
    ["Sort Loot Into Base"] = "Sort all held Loot Into Base Area containers based on item type",
    ["Clean Up Inventory"] = getText("ContextMenu_SS_OrderDesc_Clean_Up_Inventory"),
    ["Gather Wood"] = getText("ContextMenu_SS_OrderDesc_Gather_Wood"),
    ["Dismiss"] = getText("ContextMenu_SS_OrderDesc_Dismiss"),
    ["Relax"] = getText("ContextMenu_SS_OrderDesc_Relax"),
    ["Pile Corpses"] = getText("ContextMenu_SS_OrderDesc_Pile_Corpses"),
    ["Return To Base"] = getText("ContextMenu_SS_OrderDesc_Return_To_Base"),
    ["Stop"] = getText("ContextMenu_SS_OrderDesc_Stop")
};

OrderDisplayName = {
    ["Farming"] = getText("ContextMenu_SS_OrderDisplayName_Farming"),
    ["Barricade"] = getText("ContextMenu_SS_OrderDisplayName_Barricade"),
    ["Chop Wood"] = getText("ContextMenu_SS_OrderDisplayName_Chop_Wood"),
    ["Explore"] = getText("ContextMenu_SS_OrderDisplayName_Explore"),
    ["Follow"] = getText("ContextMenu_SS_OrderDisplayName_Follow"),
    ["Forage"] = getText("ContextMenu_SS_OrderDisplayName_Forage"),
    ["Guard"] = getText("ContextMenu_SS_OrderDisplayName_Guard"),
    ["Patrol"] = getText("ContextMenu_SS_OrderDisplayName_Patrol"),
    ["Stand Ground"] = getText("ContextMenu_SS_OrderDisplayName_Stand_Ground"),
    ["Loot Room"] = getText("ContextMenu_SS_OrderDisplayName_Loot_Room"),
    ["Lock Doors"] = getText("ContextMenu_SS_OrderDisplayName_Lock_Doors"),
    ["Doctor"] = getText("ContextMenu_SS_OrderDisplayName_Doctor"),
    ["Go Find Food"] = getText("ContextMenu_SS_OrderDisplayName_Go_Find_Food"),
    ["Go Find Weapon"] = getText("ContextMenu_SS_OrderDisplayName_Go_Find_Weapon"),
    ["Go Find Water"] = getText("ContextMenu_SS_OrderDisplayName_Go_Find_Water"),
    ["Clean Up Inventory"] = getText("ContextMenu_SS_OrderDisplayName_Clean_Up_Inventory"),
    ["Sort Loot Into Base"] = "Sort Loot Into Base",
    ["Gather Wood"] = getText("ContextMenu_SS_OrderDisplayName_Gather_Wood"),
    ["Dismiss"] = getText("ContextMenu_SS_OrderDisplayName_Dismiss"),
    ["Relax"] = getText("ContextMenu_SS_OrderDisplayName_Relax"),
    ["Pile Corpses"] = getText("ContextMenu_SS_OrderDisplayName_Pile_Corpses"),
    ["Return To Base"] = getText("ContextMenu_SS_OrderDisplayName_Return_To_Base"),
    ["Stop"] = getText("ContextMenu_SS_OrderDisplayName_Stop")
};
