SpawnRate 4
WifeSpawn 1
LockNLoad 1
GunSpawnRate 3
WepSpawnRate 6
HostileSpawnRate 1
MaxHostileSpawnRate 17
InfinitAmmo 2
NoPreSetSpawn 1
FindWork 1
SurvivorHunger 1
SurvivorFriendliness 4
RaidersAtLeastHours 7
RaidersAfterHours 2
RaidersChance 3
Bravery 2
SSHotkey1 6
SSHotkey2 18
SSHotkey3 27
SSHotkey4 42
SafeBase 1
DebugOptions 2
